blank_issues_enabled: true
contact_links:
  - name: 📚 项目文档
    url: https://autox-doc.vercel.app
    about: 查看项目使用文档
  - name: 💬 讨论区
    url: https://github.com/yuyin333/AutoX/discussions
    about: 参与社区讨论，分享使用经验和想法
